apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonwebappdeployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pythonwebapp
  template:
    metadata:
      name: pythonwebapppod
      labels:
        app: pythonwebapp
    spec:
      containers:
        - name: pythonwebappcontainer
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pythonwebappsvc
spec:
  selector:
    app: pythonwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
